apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    app: tekton-operator
    name: tekton-operator-webhook
  name: webhook.operator.tekton.dev
webhooks:
- admissionReviewVersions:
  - v1beta1
  - v1
  clientConfig:
    service:
      name: tekton-operator-webhook
      namespace: tekton-operator
  failurePolicy: Fail
  name: webhook.operator.tekton.dev
  sideEffects: None
