apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    operator.tekton.dev/release: devel
    version: v0.49.0
  name: tekton-operator-webhook
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tekton-operator-webhook
  template:
    metadata:
      labels:
        app: tekton-operator
        name: tekton-operator-webhook
    spec:
      containers:
      - env:
        - name: SYSTEM_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: CONFIG_LOGGING_NAME
          value: config-logging
        - name: WEBHOOK_SERVICE_NAME
          value: tekton-operator-webhook
        - name: WEBHOOK_SECRET_NAME
          value: tekton-operator-webhook-certs
        image: "{{ .Values.webhook.image.repo }}:{{ .Values.webhook.image.tag }}"
        imagePullPolicy: {{ .Values.webhook.image.pullPolicy | default "Always" }}
        name: webhook
        ports:
        - containerPort: 8443
          name: https-webhook
      serviceAccountName: tekton-operator
