apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-operator
  namespace: {{ .Release.Namespace }}
{{- if .Values.image.pullSecrets }}
imagePullSecrets:
{{- range .Values.image.pullSecrets }}
- name: {{ . }}
{{- end }}
{{- end }}
